(source gnu)
(source melpa)

(depends-on "pallet")

(depends-on "use-package")
(depends-on "magit")
(depends-on "auto-compile")
(depends-on "js3-mode")
(depends-on "coffee-mode")
(depends-on "popwin")
(depends-on "slime")
(depends-on "yaml-mode")
(depends-on "ag")
(depends-on "editorconfig")
(depends-on "flycheck")
(depends-on "flycheck-tip")
(depends-on "ddskk")
(depends-on "whitespace-cleanup-mode")
(depends-on "groovy-mode")
(depends-on "markdown-mode")
(depends-on "company")
